### ISSUE TITLE
Invites

### ISSUE THREAD

**Issue by bryonpokemon** [Its-Vichy/Disboard-Scraper#2]
first, thank you for the tool, But I have an issue with the tool, it doesn't scrape anymore servers after page 0, all tags (community, chill, social etc)

**Comment by Its-Vichy** [comment]
Thanks dude,
Do you have any errors ?

**Comment by bryonpokemon** [comment]
no, just after page 0/first page, it gets 0 result
![adc](https://user-images.githubusercontent.com/88077222/141523450-52c9bc1a-ef2e-44e7-beba-f42f48caccea.png)
s

**Comment by Its-Vichy** [comment]
Mhh idk

**Comment by bryonpokemon** [comment]
member_count option also doesn't work as well gives me 0 servers from the start and is this project still being maintained? if so, my suggestion is proxy support cause I keep getting 429: too many request errors.

**Comment by Its-Vichy** [comment]
Ok, i will check that latter ;)
